options:
  # Enable automatic updates
  auto-update: true

  # Infusion options
  infusions:
    ## Enable specific infusions (true = enabled, false = disabled)

  # Destructive crits
  infusion-destructivecrits: true
  # Phantom crits
  infusion-phantomcrits: true
  # True aim
  infusion-trueaim: true
  # Forceful
  infusion-forceful: true
  # Volatile
  infusion-volatile: true
  # Healing
  infusion-healing: true
  # Auto replant
  infusion-autoreplant: true
  # Totem battery
  infusion-totemstorage: true
  # Knockback
  infusion-knockback: true

  # Transmutation options
  transmutations:
    ## Enable specific transmutations (true = enabled, false = disabled)

  # Reinforced ingot
  reinforced-transmutation: true
  # Hardened metal
  hardened-transmutation: true
  # Steel ingot
  steel-transmutation: true
  # Damascus steel ingot
  damascus-transmutation: true
  # Compressed carbon
  compressed-carbon-transmutation: true

  # Use the corresponding Slimefun item's CustomModelData for resourcepack display and crafting
  # Not recommended to disable
  use-same-custommodeldata: true

  # Potion options
  potions:
    # Benevolent brew
    benevolent-brew:
      # Potion configuration
      # Note: Potion durations use Minecraft ticks (1 second = 20 ticks). Multiply seconds by 20 to get ticks.

      # Resistance boost
      resistance:
        ticks: 6000
        # Resistance level 5 and higher will make the player immune to almost all damage
        level: 1
      # Haste
      haste:
        ticks: 6000
        level: 2
      # Regeneration
      regen:
        ticks: 6000
        level: 2
      # Speed
      speed:
        ticks: 6000
        level: 2
      # Jump boost
      jump:
        ticks: 6000
        level: 2

  # How many extra health points are granted when drinking (yellow part of the health bar, 1 point = half a heart)
  # Must be a decimal value, e.g.: 0.0, 1.0
      absorption-halfhearts: 0.0

    # Malevolent concoction
    malevolent-concoction:
      # Potion configuration
      # Note: Potion durations use Minecraft ticks (1 second = 20 ticks). Multiply seconds by 20 to get ticks.

      # Weakness
      weakness:
        ticks: 6000
        level: 3
      # Slowness
      slowness:
        ticks: 3000
        level: 2
      # Poison
      poison:
        ticks: 600
        level: 2
      # Blindness
      blindness:
        ticks: 1200
        level: 1
      # Hunger
      hunger:
        ticks: 600
        level: 2
