blank_issues_enabled: false
contact_links:
  - name: No GitHub account? Need help using GitHub?
    url: https://ybw0014.net/go/sf-qgroup
    about: Click the button to join the QQ group for feedback
